default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tubarao_credito_development

test:
  <<: *default
  database: tubarao_credito_test

production:
  <<: *default
  database: tubarao_credito_production
  username: tubarao_credito
  password: <%= ENV["TUBARAO_CREDITO_DATABASE_PASSWORD"] %>
